### PR TITLE
Update: Blocklist.txt

### PR DESCRIPTION
**Pull request by REALSDEALS**
Update: Update on the Blocklist.txt - A lot comes back with an unreachable error or it flat out fails to even make an connection with the page/base.

'fwmrm.net' just stops the -g proces or can cause a crash.

### CODE REVIEW

**Comment by Ewpratten** [comment]
That is simply how those domains work. your PR would make this blocklist practically useless

**Comment by REALSDEALS** [comment]
I'm so sorry, I'm new to this.

I just wanted to help you out, but thanks for letting me know!

**Comment by Ewpratten** [comment]
No problem. We generally verify these domains by loading them into an adblocker then just browsing around youtube for a bit to see what works and what doesn't

Further PRs with domain additions or justified removals are welcome!

**Comment by REALSDEALS** [comment]
Thanks for the clarification! 
I really like the work you have put into it, thanks for that!

**Pull request closed without merging**
