### PR TITLE
add unbound generator

### PR DESCRIPTION
**Pull request by larsrh**
Adds a generator for the `unbound` DNS server.

### CODE REVIEW

**Comment by Owyn** [comment]
unbound can redirect all subdomains for a domain e.g.  ( https://dannyda.com/2020/06/20/how-to-use-wildcard-domain-in-unbound-for-redirection-blocking-override-domain/ )

`*.googlevideo.com`

do you know if there are subdomains there that shouldn't be blocked? @Ewpratten

**Comment by Ewpratten** [comment]
That should be fine @Owyn 

@larsrh Can you add a  link to the README file for this new list?

**Comment by larsrh** [comment]
@Ewpratten done

**Comment by Ewpratten** [comment]
Thank you!

**Comment by Owyn** [comment]
> That should be fine 

@Ewpratten 
it seems that subdomains from `*.googlevideo.com` serve actual youtube videos and not just ads ;s

my great plan has failed :-(

**Pull request merged**
